version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: sparky1225
      MYSQL_DATABASE: medicare_db
    ports:
      - "3307:3306"
    volumes:
      - ./db_data/initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql  
    networks:
      - healthcare-network
    restart: always
    healthcheck:
      test: "mysqladmin ping -h localhost -uroot -psparky1225"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medicare_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sparky1225
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8081:8080"
    networks:
      - healthcare-network
    restart: always

networks:
  healthcare-network:
    driver: bridge




